// ============================================================
// MOCK DATA
// In a real app this would be your database queries.
// This file powers all Route Handlers and Server Components.
// ============================================================

import type {
  User,
  Project,
  Task,
  TaskWithRelations,
  Comment,
  Notification,
  Workspace,
  AuthUser,
  AnalyticsOverview,
} from "@/types";

// ── Workspace ────────────────────────────────────────────────

export const mockWorkspace: Workspace = {
  id: "ws_1",
  name: "Acme Corp",
  slug: "acme-corp",
  plan: "pro",
  createdAt: "2024-01-01T00:00:00Z",
};

// ── Users ────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: "user_1",
    email: "alex@acme.com",
    name: "Alex Johnson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    role: "owner",
    createdAt: "2024-01-01T00:00:00Z",
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: "user_2",
    email: "sarah@acme.com",
    name: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    role: "admin",
    createdAt: "2024-01-05T00:00:00Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "user_3",
    email: "marcus@acme.com",
    name: "Marcus Williams",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus",
    role: "member",
    createdAt: "2024-01-10T00:00:00Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "user_4",
    email: "priya@acme.com",
    name: "Priya Patel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    role: "member",
    createdAt: "2024-02-01T00:00:00Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "user_5",
    email: "jordan@acme.com",
    name: "Jordan Kim",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
    role: "viewer",
    createdAt: "2024-03-01T00:00:00Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const mockCurrentUser: AuthUser = {
  ...mockUsers[0],
  workspace: mockWorkspace,
};

// ── Projects ─────────────────────────────────────────────────

export const mockProjects: Project[] = [
  {
    id: "proj_1",
    name: "Website Redesign",
    description: "Complete overhaul of the marketing website with new brand guidelines",
    status: "active",
    color: "#6366f1",
    ownerId: "user_1",
    memberIds: ["user_1", "user_2", "user_3"],
    taskCount: 24,
    completedTaskCount: 11,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
    dueDate: "2024-08-01T00:00:00Z",
  },
  {
    id: "proj_2",
    name: "Mobile App v2",
    description: "Feature updates and performance improvements for Q3",
    status: "active",
    color: "#8b5cf6",
    ownerId: "user_2",
    memberIds: ["user_1", "user_2", "user_4", "user_5"],
    taskCount: 38,
    completedTaskCount: 22,
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-05-22T00:00:00Z",
    dueDate: "2024-09-15T00:00:00Z",
  },
  {
    id: "proj_3",
    name: "API Integration",
    description: "Integrate with Stripe, Twilio, and third-party data providers",
    status: "active",
    color: "#14b8a6",
    ownerId: "user_1",
    memberIds: ["user_1", "user_3"],
    taskCount: 16,
    completedTaskCount: 16,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-04-30T00:00:00Z",
  },
  {
    id: "proj_4",
    name: "Q2 Marketing Campaign",
    description: "Content, social, and paid campaigns for Q2 launch",
    status: "completed",
    color: "#f43f5e",
    ownerId: "user_4",
    memberIds: ["user_2", "user_4", "user_5"],
    taskCount: 20,
    completedTaskCount: 20,
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-04-15T00:00:00Z",
  },
  {
    id: "proj_5",
    name: "Infrastructure Migration",
    description: "Move from AWS EC2 to Kubernetes on GKE",
    status: "active",
    color: "#f97316",
    ownerId: "user_3",
    memberIds: ["user_1", "user_3"],
    taskCount: 12,
    completedTaskCount: 3,
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-05-23T00:00:00Z",
    dueDate: "2024-10-01T00:00:00Z",
  },
];

// ── Tasks ────────────────────────────────────────────────────

export const mockTasks: Task[] = [
  // Website Redesign tasks
  {
    id: "task_1",
    title: "Design new homepage hero section",
    description: "Create wireframes and hi-fi mockups for the above-the-fold hero. Consider mobile first.",
    status: "done",
    priority: "high",
    projectId: "proj_1",
    assigneeId: "user_2",
    creatorId: "user_1",
    labels: ["design", "frontend"],
    estimate: 5,
    dueDate: "2024-05-15T00:00:00Z",
    completedAt: "2024-05-14T00:00:00Z",
    order: 0,
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-05-14T00:00:00Z",
  },
  {
    id: "task_2",
    title: "Implement navigation component",
    description: "Build the responsive nav with dropdown menus and mobile hamburger.",
    status: "in_progress",
    priority: "high",
    projectId: "proj_1",
    assigneeId: "user_3",
    creatorId: "user_1",
    labels: ["frontend"],
    estimate: 3,
    dueDate: "2024-06-01T00:00:00Z",
    order: 1,
    createdAt: "2024-04-05T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
  },
  {
    id: "task_3",
    title: "Write copy for features page",
    description: "Draft compelling copy for each feature section. Work with marketing for tone.",
    status: "todo",
    priority: "medium",
    projectId: "proj_1",
    assigneeId: "user_2",
    creatorId: "user_2",
    labels: ["content"],
    estimate: 2,
    order: 2,
    createdAt: "2024-04-10T00:00:00Z",
    updatedAt: "2024-04-10T00:00:00Z",
  },
  {
    id: "task_4",
    title: "SEO audit and implementation",
    description: "Conduct a full SEO audit and implement structured data, meta tags, and sitemap.",
    status: "backlog",
    priority: "medium",
    projectId: "proj_1",
    creatorId: "user_1",
    labels: ["seo", "marketing"],
    estimate: 8,
    order: 3,
    createdAt: "2024-04-12T00:00:00Z",
    updatedAt: "2024-04-12T00:00:00Z",
  },
  {
    id: "task_5",
    title: "Performance optimization — Core Web Vitals",
    description: "Hit 90+ Lighthouse scores. Focus on LCP, CLS, FID.",
    status: "todo",
    priority: "urgent",
    projectId: "proj_1",
    assigneeId: "user_3",
    creatorId: "user_1",
    labels: ["performance", "frontend"],
    estimate: 5,
    dueDate: "2024-06-15T00:00:00Z",
    order: 4,
    createdAt: "2024-04-15T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  // Mobile App v2 tasks
  {
    id: "task_6",
    title: "Push notification system",
    description: "Implement Firebase Cloud Messaging for iOS and Android.",
    status: "in_review",
    priority: "high",
    projectId: "proj_2",
    assigneeId: "user_4",
    creatorId: "user_2",
    labels: ["mobile", "backend"],
    estimate: 8,
    dueDate: "2024-06-10T00:00:00Z",
    order: 0,
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-05-22T00:00:00Z",
  },
  {
    id: "task_7",
    title: "Offline mode with local caching",
    description: "Implement SQLite-backed offline mode with sync queue.",
    status: "in_progress",
    priority: "high",
    projectId: "proj_2",
    assigneeId: "user_3",
    creatorId: "user_2",
    labels: ["mobile"],
    estimate: 13,
    order: 1,
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-05-21T00:00:00Z",
  },
  {
    id: "task_8",
    title: "Dark mode support",
    description: "Full dark mode implementation following system preferences.",
    status: "done",
    priority: "medium",
    projectId: "proj_2",
    assigneeId: "user_4",
    creatorId: "user_2",
    labels: ["mobile", "design"],
    estimate: 5,
    completedAt: "2024-04-20T00:00:00Z",
    order: 2,
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-04-20T00:00:00Z",
  },
  {
    id: "task_9",
    title: "App store screenshots and listing",
    description: "Create marketing screenshots for both iOS and Android stores.",
    status: "todo",
    priority: "low",
    projectId: "proj_2",
    assigneeId: "user_5",
    creatorId: "user_2",
    labels: ["marketing"],
    estimate: 3,
    order: 3,
    createdAt: "2024-04-10T00:00:00Z",
    updatedAt: "2024-04-10T00:00:00Z",
  },
  {
    id: "task_10",
    title: "Biometric authentication",
    description: "Face ID / fingerprint login via device biometrics.",
    status: "backlog",
    priority: "medium",
    projectId: "proj_2",
    creatorId: "user_2",
    labels: ["security", "mobile"],
    estimate: 5,
    order: 4,
    createdAt: "2024-04-15T00:00:00Z",
    updatedAt: "2024-04-15T00:00:00Z",
  },
  // Infrastructure tasks
  {
    id: "task_11",
    title: "Set up GKE cluster",
    description: "Provision production-grade GKE cluster with node autoscaling.",
    status: "done",
    priority: "urgent",
    projectId: "proj_5",
    assigneeId: "user_3",
    creatorId: "user_3",
    labels: ["devops", "infrastructure"],
    estimate: 8,
    completedAt: "2024-05-01T00:00:00Z",
    order: 0,
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "task_12",
    title: "Write Helm charts for all services",
    description: "Templatize all service deployments using Helm v3.",
    status: "in_progress",
    priority: "high",
    projectId: "proj_5",
    assigneeId: "user_3",
    creatorId: "user_3",
    labels: ["devops"],
    estimate: 13,
    order: 1,
    createdAt: "2024-04-05T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "task_13",
    title: "Configure horizontal pod autoscaler",
    description: "Set up HPA for all stateless services based on CPU and memory metrics.",
    status: "todo",
    priority: "medium",
    projectId: "proj_5",
    assigneeId: "user_1",
    creatorId: "user_3",
    labels: ["devops"],
    estimate: 5,
    order: 2,
    createdAt: "2024-04-10T00:00:00Z",
    updatedAt: "2024-04-10T00:00:00Z",
  },
];

// ── Task with relations ───────────────────────────────────────

export function getTaskWithRelations(task: Task): TaskWithRelations {
  const project = mockProjects.find((p) => p.id === task.projectId)!;
  const assignee = task.assigneeId ? mockUsers.find((u) => u.id === task.assigneeId) : undefined;
  const creator = mockUsers.find((u) => u.id === task.creatorId)!;

  return {
    ...task,
    project: { id: project.id, name: project.name, color: project.color },
    assignee: assignee
      ? { id: assignee.id, name: assignee.name, avatar: assignee.avatar }
      : undefined,
    creator: { id: creator.id, name: creator.name, avatar: creator.avatar },
  };
}

export const mockTasksWithRelations: TaskWithRelations[] = mockTasks.map(getTaskWithRelations);

// ── Comments ─────────────────────────────────────────────────

export const mockComments: Comment[] = [
  {
    id: "comment_1",
    content: "I've started the wireframes — will share in Figma by EOD.",
    taskId: "task_1",
    authorId: "user_2",
    author: { id: "user_2", name: "Sarah Chen", avatar: mockUsers[1].avatar },
    createdAt: "2024-05-10T09:00:00Z",
    updatedAt: "2024-05-10T09:00:00Z",
  },
  {
    id: "comment_2",
    content: "Looks great! One note — can we make the CTA button more prominent?",
    taskId: "task_1",
    authorId: "user_1",
    author: { id: "user_1", name: "Alex Johnson", avatar: mockUsers[0].avatar },
    createdAt: "2024-05-12T14:30:00Z",
    updatedAt: "2024-05-12T14:30:00Z",
  },
];

// ── Notifications ─────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: "notif_1",
    type: "task_assigned",
    title: "New task assigned",
    body: 'You were assigned "Configure horizontal pod autoscaler"',
    read: false,
    userId: "user_1",
    actorId: "user_3",
    actor: { id: "user_3", name: "Marcus Williams", avatar: mockUsers[2].avatar },
    entityId: "task_13",
    entityType: "task",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "notif_2",
    type: "task_comment",
    title: "New comment",
    body: 'Sarah commented on "Design new homepage hero section"',
    read: false,
    userId: "user_1",
    actorId: "user_2",
    actor: { id: "user_2", name: "Sarah Chen", avatar: mockUsers[1].avatar },
    entityId: "task_1",
    entityType: "task",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "notif_3",
    type: "task_status_changed",
    title: "Task status updated",
    body: '"Push notification system" moved to In Review',
    read: true,
    userId: "user_1",
    actorId: "user_4",
    actor: { id: "user_4", name: "Priya Patel", avatar: mockUsers[3].avatar },
    entityId: "task_6",
    entityType: "task",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "notif_4",
    type: "mention",
    title: "You were mentioned",
    body: 'Marcus mentioned you in "Write Helm charts for all services"',
    read: true,
    userId: "user_1",
    actorId: "user_3",
    actor: { id: "user_3", name: "Marcus Williams", avatar: mockUsers[2].avatar },
    entityId: "task_12",
    entityType: "task",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

// ── Analytics ─────────────────────────────────────────────────

export const mockAnalytics: AnalyticsOverview = {
  total_tasks: 98,
  completed_tasks: 52,
  active_projects: 4,
  team_members: 5,
  completion_rate: 53.1,
  period_data: [
    { label: "Jan", tasks_completed: 8, tasks_created: 15, active_members: 3 },
    { label: "Feb", tasks_completed: 12, tasks_created: 18, active_members: 4 },
    { label: "Mar", tasks_completed: 10, tasks_created: 22, active_members: 4 },
    { label: "Apr", tasks_completed: 16, tasks_created: 14, active_members: 5 },
    { label: "May", tasks_completed: 14, tasks_created: 19, active_members: 5 },
    { label: "Jun", tasks_completed: 6, tasks_created: 10, active_members: 5 },
  ],
  tasks_by_priority: {
    urgent: 6,
    high: 18,
    medium: 32,
    low: 14,
    no_priority: 28,
  },
  tasks_by_status: {
    backlog: 18,
    todo: 24,
    in_progress: 12,
    in_review: 4,
    done: 34,
    cancelled: 6,
  },
};
